name: Check docs build cleanly

# on:
#   # Run on pushes to main
#   push:
#     branches:
#       - build_docs
#   # And all pull requests
#   pull_request:

on:
  pull_request:
    types:
      - opened
    branches:
      - 'dolci/build_docs'
concurrency:
  # Cancels jobs running if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_docs:
    name: Run doc build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-docdeps:latest
      options: --user root
      volumes:
        - ${{ github.workspace }}:/home/firedrake/output
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - uses: actions/checkout@v3
      - name: Install chekpoint_schedules
        run: |
          python -m pip install -e .
      - name: Check bibtex
        run: |
          cd docs
          make validate-bibtex
      - name: Check documentation links
        if: ${{ github.ref == 'refs/heads/build_docs' }}
        run: |
          cd docs
          make linkcheck
      - name: Build docs
        run: |
          cd docs
          make html
          make latex
          make latexpdf
      - name: Copy manual to HTML tree
        run: |
          cd docs
          cp build/latex/checkpoint_schedules.pdf build/html/_static/manual.pdf
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: /__w/checkpoint_schedules/checkpoint_schedules/docs/build/html
          retention-days: 1
  deploy:
    name: Deploy Github pages
    needs: build_docs
    if: ${{ github.ref == 'refs/heads/build_docs' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: http://firedrakeproject.github.io/checkpoint_schedules
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2