name: Check docs build cleanly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    name: "Run doc build"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          python -m pip install -e .
          python -m pip install sphinx
          python -m pip install sphinxcontrib-bibtex
          python -m pip install sphinxcontrib-svg2pdfconverter
          python -m pip install bibtexparser
          python -m pip install numpydoc
      - name: Build docs
        run: |
          cd docs
          sh makedoc.sh
          # make latex
          # make latexpdf
